# Generated by Django 3.2.7 on 2021-10-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDoadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField(max_length=20)),
                ('endereco', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('telefonefixo', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('Intencao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QtDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade (l)')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('d_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cadastrodoadores')),
            ],
        ),
    ]
