# Generated by Django 3.2.7 on 2021-10-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qtdoacao',
            old_name='d_cpf',
            new_name='d_celular',
        ),
        migrations.RemoveField(
            model_name='cadastrodoadores',
            name='cpf',
        ),
    ]
